profile: dev

database:
  engine:
  user:
  password:
  host:
  port:
  dbname:

logging:
    graylog:
      host: 0.0.0.0
      port: 9000
      enabled: false
      udp: true
    console:
      enabled: false
    root_level: INFO
    levels:
      httpx: WARN
      openai: WARN
      uvicorn.access: WARN